CLASS zbp_mhp_u_travel_prepared_xxx DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
*  FOR BEHAVIOR OF zi_mhp_travel_u_xxx
  .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_MHP_U_TRAVEL_PREPARED_XXX IMPLEMENTATION.
ENDCLASS.
